### PR TITLE
CS Audit, LIME-165, fixed poolToken decimals issue

### PR DESCRIPTION
**Pull request by saxenism**
## Description

Pool contract extends ERC20PausableUpgradeable which uses as default 18 decimals. The amount of pool tokens minted corresponds to the amount of the borrow asset lent to the pool. In other words, the Pool contract ignores the decimals of the borrow asset and for 1 Wei of borrow token sent to the pool, it mints 1 Wei of the pool token, despite the borrow asset might have different decimals. Although the accounting works for the contract, integrating with external components, e.g., UI, is prone to errors.

## Change Log

The decimals of the PoolToken have been shifted from the default 18 to the decimals of the borrowToken. Relevant changes were made to the tests.

## Function signature changes

`Pool:lend` function's signature was changed.
Earlier:
```
    function lend(
        address _lender,
        uint256 _amount,
        bool _fromSavingsAccount
    ) external payable nonReentrant {
```

Now
```
    function lend(
        address _lender,
        uint256 _amount,
        address _strategy
    ) external payable nonReentrant {
```

### CODE REVIEW

**Comment by prateekreddy** [comment]
@saxenism Can you separate the various changes into different PRs ? All the changes  in PR  are not related to the poolToken decimals issue

**Review by prateekreddy — CHANGES_REQUESTED** [review]
@saxenism Can you separate the various changes into different PRs ? All the changes in PR are not related to the poolToken decimals issue

**Comment by saxenism** [comment]
> @saxenism Can you separate the various changes into different PRs ? All the changes in PR are not related to the poolToken decimals issue

This branch got a bit too messy, so I've made the required changes in a new branch and hence, a new PR. So, please review PR #294 and after you're done, I'll delete this branch and PR.

@prateekreddy @ritik99

**Comment by ritik99** [comment]
Can delete

**Pull request closed without merging**
