### PR TITLE
Fix withdrawable collateral in case of liquidations

### PR DESCRIPTION
**Pull request by prateekreddy**

### CODE REVIEW

**Comment by KalpitaMandal** [comment]
In case of `EXPIRED` status, if a borrower has not borrowed anything from the PooledCreditline and has deposited collateral. He should be able to get his totalCollateral tokens back, right? But in the current scenario, the user will not be able to get back his collateral if he calls withdrawCollateral function. Is that the desired scenario or does the borrower have to go and do all the pool operations (borrow, repay, etc) to get back his collateral?

**Comment by prateekreddy** [comment]
> In case of `EXPIRED` status, if a borrower has not borrowed anything from the PooledCreditline and has deposited collateral. He should be able to get his totalCollateral tokens back, right? But in the current scenario, the user will not be able to get back his collateral if he calls withdrawCollateral function. Is that the desired scenario or does the borrower have to go and do all the pool operations (borrow, repay, etc) to get back his collateral?

True.... I have allowed closing of pool in expired state as well as long as principal is 0. That should fix this.

**Review by ritik99 — APPROVED** [review]
Merge conflicts need to be resolved

**Review by KalpitaMandal — APPROVED** [review]
lgtm

**Comment by ritik99** [comment]
lgtm

**Pull request merged**
